# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'blog-thisisrajat'

google-ID: 'UA-108379257-2'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/thisisrajat'}
- {icon: 'instagram', link: 'https://instagram.com/thisisrajat'}
- {icon: 'envelope', link: 'mailto:rajat@rajatja.in'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
